### ISSUE TITLE
Question about ticket generator

### ISSUE THREAD

**Issue by second-reality** [Tsume/Mapleseed#2]
Hi Tsume,

wanted to know how you found how ticket is generated?
Did you reverse engineered it, or did you found it in another program/forum?

    data.insert(0x1E6, QByteArray::fromHex(ver.toLatin1()));
    data.insert(0x1BF, QByteArray::fromHex(key.toLatin1()));
    data.insert(0x2CC, QByteArray::fromHex(id.toLatin1()));

Thank you,
Pierrick

**Comment by Tsume** [comment]
Wasn't aware of this question, until now. Normally I get an email.

To answer your question, I pulled the structure from cdecrypt. Though it took some trial and error figuring out what format to use. The entire decryption process was originally based on cdecrypt. Still is for the majority with minor changes to better integrate it into the C++ builds of MS.

**Comment by second-reality** [comment]
Thank you very much for your answer.

Very nice work you did :)
