### ISSUE TITLE
Memory Leak while decrypting games

### ISSUE THREAD

**Issue by nhh** [Tsume/Mapleseed#3]
The current implementation eats up all my existing memory when decrypting files.

It might be a memory leak, or is it somewhat intentional?

![image](https://user-images.githubusercontent.com/13472382/75089345-05bd5a80-5558-11ea-8b1f-88892755e2ed.png)

**Comment by tacrazymage** [comment]
decrypting wont work at all for me
and games wont start with cemu

**Comment by Caf** [comment]
Yep, it just don't work. Sadly. :( We need @Tsume   ;)   https://www.reddit.com/r/MapleSeed/comments/facqk7/decryption_exit_code_0_on_the_new_mapleseed/

**Comment by Tsume** [comment]
I'm not home at the moment. Haven't been for a while. But a fix is coming soon(hopefully). #ThanksCorona

**Comment by Caf** [comment]
> I'm not home at the moment. Haven't been for a while. But a fix is coming soon(hopefully). #ThanksCorona

Damn. Take care! We are (well, I am) stuck at home and that's why we do toy with this. ;)

**Comment by Tsume** [comment]
Try this and see what happens. *hasn't been tested*.

**Comment by Caf** [comment]
> 
> 
> Try this and see what happens. _hasn't been tested_.
> 
> https://tsumes.com/mapleseed/mapleseed.test.zip

It's DIFFERENT. :D Crashing at the end of a DL now. ;) (program not responding). ;)

**Comment by Tsume** [comment]
I figured it wouldn’t work lol. The last build when i was reimplementing the decryption. Easy fix.

**Comment by Caf** [comment]
I hope you'll come around to fix this. :) Anyway, thx again for this project  👍

**Comment by Tsume** [comment]
Memory issues should have been resolved in the new console releases.
Should be able to start working on this project again soon.
